api:
  needs: [build-api]
  imagePackage: api
  probesPath: /healthz
  containerPort: 2626

app:
  needs: [build-app]
  imagePackage: app
  probesPath: /healthz
  containerPort: 3000

declaration:
  needs: [build-declaration]
  imagePackage: declaration
  probesPath: /index.html
  containerPort: 8080

simulateur:
  needs: [build-simulateur]
  imagePackage: simulateur
  probesPath: /index.html
  containerPort: 8080

jobs:
  runs:
    build-api:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: api
        context: packages/api

    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: app
        dockerfile: packages/app/Dockerfile

    build-declaration:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: declaration
        context: packages/declaration

    build-simulateur:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: simulateur
        dockerfile: packages/simulateur/Dockerfile