app:
  needs: [build-app]
  imagePackage: app
  probesPath: /consulter-index/healthz
  containerPort: 3000
  host: "{{ .Values.global.host }}"
  ~ingress.path: /consulter-index(/|$)(.*)

app-api:
  needs: [build-api]
  imagePackage: api
  probesPath: /healthz
  containerPort: 2626
  host: "{{ .Values.global.host }}"
  ~ingress.path: /api(/|$)(.*)
  ~ingress.rewriteTarget: /$2
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
  vars:
    EGAPRO_DBHOST: "$(PGHOST)"
    EGAPRO_DBNAME: "$(PGDATABASE)"
    EGAPRO_DBPORT: "$(PGPORT)"
    EGAPRO_DBUSER: "$(PGUSER)"
    EGAPRO_DBPASS: "$(PGPASSWORD)"
    EGAPRO_DBSSL: "$(PGSSLMODE)"

app-declaration:
  needs: [build-declaration]
  imagePackage: declaration
  probesPath: /index.html
  containerPort: 8080
  host: "{{ .Values.global.host }}"
  ~ingress.path: /declaration(/|$)(.*)
  ~ingress.rewriteTarget: /$2

app-simulateur:
  needs: [build-simulateur]
  imagePackage: simulateur
  probesPath: /index.html
  containerPort: 8080
  host: "{{ .Values.global.host }}"
  ~ingress.path: /

jobs:
  runs:
    build-app:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: app
        dockerfile: packages/app/Dockerfile
    
    build-api:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: api
        context: packages/api

    build-declaration:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: declaration
        context: packages/declaration
        buildArgs:
          BASE_URL: "https://{{ .Values.global.host }}/declaration"
          EGAPRO_API_URL: "https://{{ .Values.global.host }}/api"

    build-simulateur:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/build
      with:
        imagePackage: simulateur
        dockerfile: packages/simulateur/Dockerfile
        buildArgs:
          REACT_APP_EGAPRO_API_URL: "https://{{ .Values.global.host }}/api"
          REACT_APP_DECLARATION_URL: "https://{{ .Values.global.host }}/declaration"