on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create a release for Egapro-next

jobs:
  build:
    name: Create a release for Egapro-next
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile --force --non-interactive

      - name: Build app
        run: yarn build
        env:
          CI: false
          NEXT_PUBLIC_API_URL: "https://index-egapro.travail.gouv.fr/api"

      - name: Export app
        run: yarn export

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false