name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - uses: SocialGouv/actions/autodevops-release@v1
      with:
        author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
        github-token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        
    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile --force --non-interactive
        
    - name: Build app
      run: yarn build
      env:
        CI: false
        NEXT_PUBLIC_API_URL: "https://index-egapro.travail.gouv.fr/api"

    - name: Export app
      run: yarn export

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'out'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

